[profile.default]

src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"

# Advanced Optimization Settings
optimizer = true                  # Enable the optimizer
optimizer_runs = 10       # Higher value optimizes for frequent function calls
via_ir = true                    # Enable new IR-based optimizer
bytecode_hash = "none"           # Reduce bytecode size
no_storage_caching = true        # Additional gas optimization

# Function Inlining
inline_assembly = true           # Allow inline assembly
inline_yul = true               # Enable Yul inlining

# Size Optimization  
contract_size_limit = 24576     # Maximum contract size in bytes

# Metadata Settings
metadata_hash = "none"          # Remove metadata hash
cbor_metadata = false           # Disable CBOR metadata

# Gas reporting
gas_reports = ["*"]
gas_reports_ignore = ["Mock", "Test"]

# Testing configuration 
verbosity = 3
ffi = false
fs_permissions = [{ access = "read", path = "./"}]

[profile.production]
# More aggressive optimization for production
optimizer_runs = 10
via_ir = true
no_storage_caching = true

[rpc_endpoints]
sepolia = "${RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = false
int_types = "long"
multiline_func_header = "all"
quote_style = "double"
number_underscore = "thousands"

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
